name: Insert Commit ID

on:
  push:
    branches:
      - main

jobs:
  insert-commit:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short Commit ID
        id: commit
        run: |
          SHORT_COMMIT=$(git rev-parse --short=7 HEAD)
          echo "COMMIT_ID=$SHORT_COMMIT" >> $GITHUB_ENV

      - name: Insert Commit ID to PostgreSQL DB
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Inserting commit $COMMIT_ID into DB"
          psql -h ${{ secrets.DB_HOST }} \
               -U ${{ secrets.DB_USER }} \
               -d ${{ secrets.DB_NAME }} \
               -c "INSERT INTO commit_log (commit_id) VALUES ('$COMMIT_ID');"
