name: Insert Commit into PostgreSQL

on:
  pull_request:
    types: [opened, synchronize]   # Runs when PR is created/updated

jobs:
  insert-commit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          PGPASSWORD=$DB_PASSWORD psql \
            -h 127.0.0.1 \
            -p 5432 \
            -U $DB_USER \
            -d $DB_NAME \
            -c "INSERT INTO commit_log (commit_id) VALUES ('${{ github.sha }}');"
